#import "BeaconExportModule.h"

// Swift interface for the app target (generated by Xcode from the Swift sources).
// This file is compiled as Objective-C++ without Clang modules, so every framework the
// generated header mentions must be imported first. Keep the Objective-C-visible surface of
// the Swift classes small (see ExportManager.swift) so this list stays short.
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "Beacon-Swift.h"

@interface BeaconExportModule ()
@property (nonatomic, strong, readonly) BeaconExportManager *manager;
@end

@implementation BeaconExportModule

+ (NSString *)moduleName
{
  return @"BeaconExport";
}

- (instancetype)init
{
  if (self = [super init]) {
    _manager = [BeaconExportManager new];
  }
  return self;
}

- (void)writeTemporaryFile:(NSString *)fileName
                  contents:(NSString *)contents
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject
{
  [self.manager writeTemporaryFile:fileName
                          contents:contents
                        completion:^(NSString *path, NSDictionary<NSString *, id> *error) {
                          if (error != nil) {
                            [BeaconExportModule rejectWith:error reject:reject];
                          } else {
                            resolve(path);
                          }
                        }];
}

- (void)shareFile:(NSString *)path
         mimeType:(NSString *)mimeType
          resolve:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject
{
  [self.manager shareFile:path
                 mimeType:mimeType
               completion:^(BOOL shared, NSDictionary<NSString *, id> *error) {
                 if (error != nil) {
                   [BeaconExportModule rejectWith:error reject:reject];
                 } else {
                   // @YES / @NO rather than @(shared): the bridge only turns an NSNumber into
                   // a JavaScript boolean when it is a boolean NSNumber, and whether @() gives
                   // one depends on how BOOL is defined for the architecture.
                   resolve(shared ? @YES : @NO);
                 }
               }];
}

- (void)clearTemporaryFiles:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [self.manager clearTemporaryFiles:^(NSInteger removed) {
    resolve(@(removed));
  }];
}

/// Rejects with the contract `code` and message from an `ExportError.payload` dictionary so
/// JavaScript's `toExportError` can read the code off the rejection.
+ (void)rejectWith:(NSDictionary<NSString *, id> *)error reject:(RCTPromiseRejectBlock)reject
{
  NSString *code = error[@"code"] ?: @"export_unknown";
  NSString *message = error[@"message"] ?: code;
  reject(code,
         message,
         [NSError errorWithDomain:@"com.beacon.export"
                             code:0
                         userInfo:@{NSLocalizedDescriptionKey : message}]);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeBeaconExportSpecJSI>(params);
}

@end
