#import "BeaconBluetoothModule.h"

// Swift interface for the app target (generated by Xcode from the Swift sources).
// This file is compiled as Objective-C++ without Clang modules, so every framework the
// generated header mentions must be imported first. Keep the Objective-C-visible surface of
// the Swift classes small (see BluetoothManager.swift) so this list stays short.
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "Beacon-Swift.h"

@interface BeaconBluetoothModule ()
@property (nonatomic, strong, readonly) BeaconBluetoothManager *manager;
@end

@implementation BeaconBluetoothModule

+ (NSString *)moduleName
{
  return @"BeaconBluetooth";
}

- (instancetype)init
{
  if (self = [super init]) {
    _manager = [BeaconBluetoothManager new];
    __weak __typeof(self) weakSelf = self;
    _manager.onStateChanged = ^(NSString *state) {
      [weakSelf emitOnBluetoothStateChanged:@{@"state" : state}];
    };
    _manager.onDeviceDiscovered = ^(NSDictionary<NSString *, id> *device) {
      [weakSelf emitOnDeviceDiscovered:device];
    };
    _manager.onError = ^(NSDictionary<NSString *, id> *error) {
      [weakSelf emitOnBleError:@{@"error" : error}];
    };
  }
  return self;
}

- (void)getBluetoothState:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [self.manager getBluetoothState:^(NSString *state) {
    resolve(state);
  }];
}

- (void)getPermissionState:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [self.manager getPermissionState:^(NSString *state) {
    resolve(state);
  }];
}

- (void)requestPermission:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [self.manager requestPermission:^(NSString *state) {
    resolve(state);
  }];
}

- (void)startScan:(NSArray *)serviceUuids
   allowDuplicates:(BOOL)allowDuplicates
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject
{
  NSMutableArray<NSString *> *uuids = [NSMutableArray arrayWithCapacity:serviceUuids.count];
  for (id value in serviceUuids) {
    if ([value isKindOfClass:[NSString class]]) {
      [uuids addObject:value];
    }
  }
  [self.manager startScan:uuids
          allowDuplicates:allowDuplicates
               completion:^(NSDictionary<NSString *, id> *error) {
                 [BeaconBluetoothModule settle:error resolve:resolve reject:reject];
               }];
}

- (void)stopScan:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [self.manager stopScan:^(NSDictionary<NSString *, id> *error) {
    [BeaconBluetoothModule settle:error resolve:resolve reject:reject];
  }];
}

/// Resolves a void promise, or rejects it with the contract `code` and message from a
/// `BleError.payload` dictionary so JavaScript's `toBleError` can read the code.
+ (void)settle:(NSDictionary<NSString *, id> *)error
       resolve:(RCTPromiseResolveBlock)resolve
        reject:(RCTPromiseRejectBlock)reject
{
  if (error == nil) {
    resolve(nil);
    return;
  }
  NSString *code = error[@"code"] ?: @"unknown";
  NSString *message = error[@"message"] ?: code;
  NSMutableDictionary *userInfo = [NSMutableDictionary dictionaryWithObject:message
                                                                     forKey:NSLocalizedDescriptionKey];
  if (error[@"nativeCode"] != nil) {
    userInfo[@"nativeCode"] = error[@"nativeCode"];
  }
  if (error[@"nativeDomain"] != nil) {
    userInfo[@"nativeDomain"] = error[@"nativeDomain"];
  }
  reject(code, message, [NSError errorWithDomain:@"com.beacon.bluetooth" code:0 userInfo:userInfo]);
}

- (void)invalidate
{
  [self.manager invalidate];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeBeaconBluetoothSpecJSI>(params);
}

@end
