#import "BeaconBluetoothModule.h"

// Swift interface for the app target (generated by Xcode from the Swift sources).
#import "Beacon-Swift.h"

@interface BeaconBluetoothModule ()
@property (nonatomic, strong, readonly) BeaconBluetoothManager *manager;
@end

@implementation BeaconBluetoothModule

+ (NSString *)moduleName
{
  return @"BeaconBluetooth";
}

- (instancetype)init
{
  if (self = [super init]) {
    _manager = [BeaconBluetoothManager new];
    __weak __typeof(self) weakSelf = self;
    _manager.onStateChanged = ^(NSString *state) {
      [weakSelf emitOnBluetoothStateChanged:@{@"state" : state}];
    };
  }
  return self;
}

- (void)getBluetoothState:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject
{
  [self.manager getBluetoothState:^(NSString *state) {
    resolve(state);
  }];
}

- (void)invalidate
{
  [self.manager invalidate];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeBeaconBluetoothSpecJSI>(params);
}

@end
